layout_spectrum: 0.2701836
typography_spectrum: 0.250181
color:
  saturation: 0.1384497
  lightness: 0.2954136
  brandStrength: 0.40919
  rhythmicContrast: 0.9957107
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: csjones
